/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cat.CatfishBrowser;

import com.formdev.flatlaf.intellijthemes.FlatNordIJTheme;
import java.awt.Component;
import java.awt.Container;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author LynxJr
 */
public class Settings extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Settings.class.getName());
     private String previousTheme;

    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
        
        // Auto-select saved theme in combo box
        String savedTheme = ThemeUtil.getSavedTheme();
        jComboBox1.setSelectedItem(savedTheme);

        // Apply theme immediately when selecting in combo box
        previousTheme = "Nord"; 

        jComboBox1.addActionListener(e -> {
            String selectedTheme = (String) jComboBox1.getSelectedItem();

            // Attempt to set theme
            boolean applied = trySetThemeWithWarning(selectedTheme);

            // If the user cancelled, restore the previous selection
            if (!applied) {
                jComboBox1.setSelectedItem(previousTheme);
            } else {
                previousTheme = selectedTheme; // Update previousTheme
            }
        });

        // Save button stores theme permanently
        saveButton.addActionListener(e -> {
            String selectedTheme = (String) jComboBox1.getSelectedItem();
    ThemeUtil.setTheme(selectedTheme); // Apply theme
    ThemeUtil.saveTheme(selectedTheme); // Save preference
    previousTheme = selectedTheme;       // Update previousTheme
    dispose(); // close settings window
        });
    }
    
    private boolean trySetThemeWithWarning(String themeName) {
        try {
            // --- Warn user for certain themes ---
            if (themeName.equals("Windows Classic") && !ThemeUtil.isWindows()) {
                int result = JOptionPane.showOptionDialog(
                        this,
                        "This theme is Windows only. Setting this in other operating systems might not work.\n"
                                + "This is a white theme; some buttons might be hard to see.",
                        "Warning",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE,
                        null,
                        new String[]{"Set it anyway", "Cancel"},
                        "Cancel"
                );
                if (result != JOptionPane.YES_OPTION) return false; // user cancelled
            } else if (themeName.equals("Metal") || themeName.equals("Nimbus")
                    || themeName.equals("CDE/Motif") || themeName.equals("System Default")) {
                int result = JOptionPane.showOptionDialog(
                        this,
                        "This is a white theme; some buttons and labels might be hard to see.",
                        "Warning",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE,
                        null,
                        new String[]{"Set it anyway", "Cancel"},
                        "Cancel"
                );
                if (result != JOptionPane.YES_OPTION) return false; // user cancelled
            }

            // Apply theme
            ThemeUtil.setTheme(themeName);
            return true;

        } catch (Exception ex) {
            ex.printStackTrace();
            return false;
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel1.setText("Settings");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nord", "Metal", "Nimbus", "CDE/Motif", "Windows Classic", "System Default", "FlatLaf Dark", "FlatLaf Darcula", "Arc Dark", "Arc Dark - Orange", "Carbon", "Cobalt 2", "Dark Flat", "Dark Purple", "Dracula", "Gradianto Dark Fuchsia", "Gradianto Deep Ocean", "Gradianto Midnight Blue", "Gradianto Nature Green", "Gruvbox Dark Hard", "Hiberbee Dark", "High Contrast", "Material Design Dark", "Monocai", "Monokai Pro", "One Dark", "Solarized Dark", "Spacegray", "Vuesion", "Xcode-Dark" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Light Themes Coming soon!");

        saveButton.setText("Save");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(351, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Themes", jPanel1);

        jLabel2.setText("Coming soon 👀");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(430, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Coming Soon", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        ThemeUtil.applySavedTheme();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Settings().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
